name:                 mycelial
version:              0.1.0.0
visibility:           public
id:                   mycelial-0.1.0.0-inplace
key:                  mycelial-0.1.0.0-inplace
license:              MIT
maintainer:           architect@mycelial.net
author:               System Architect
abi:                  inplace
exposed:              True
exposed-modules:
    MycelialPhysics MycelialSimulation MycelialState MycelialStrategy
    Simulation.Accessors Simulation.Evolution Simulation.Lifecycle
    Simulation.Loop Simulation.Macro Simulation.Micro Simulation.Types

import-dirs:
    /home/nicoluarte/Documents/repos/phd_DCCS/coursework/ABM/mushroomBrain/dist-newstyle/build/x86_64-linux/ghc-9.6.7/mycelial-0.1.0.0/build

library-dirs:
    /home/nicoluarte/Documents/repos/phd_DCCS/coursework/ABM/mushroomBrain/dist-newstyle/build/x86_64-linux/ghc-9.6.7/mycelial-0.1.0.0/build

library-dirs-static:
    /home/nicoluarte/Documents/repos/phd_DCCS/coursework/ABM/mushroomBrain/dist-newstyle/build/x86_64-linux/ghc-9.6.7/mycelial-0.1.0.0/build

dynamic-library-dirs:
    /home/nicoluarte/Documents/repos/phd_DCCS/coursework/ABM/mushroomBrain/dist-newstyle/build/x86_64-linux/ghc-9.6.7/mycelial-0.1.0.0/build

data-dir:
    /home/nicoluarte/Documents/repos/phd_DCCS/coursework/ABM/mushroomBrain/.

hs-libraries:         HSmycelial-0.1.0.0-inplace
depends:
    aeson-2.2.3.0-740d279ab2fa7e04dc3118355747e72bd7f6e8952231b398993affab656a9646
    base-4.18.3.0 bytestring-0.11.5.4 containers-0.6.7 mtl-2.3.1
    random-1.3.1-a0b546c9357ed7f48cc7d509a46d4c9a14b6798796f7e850ba3aa653db265e47
    text-2.0.2

haddock-interfaces:
    /home/nicoluarte/Documents/repos/phd_DCCS/coursework/ABM/mushroomBrain/dist-newstyle/build/x86_64-linux/ghc-9.6.7/mycelial-0.1.0.0/doc/html/mycelial/mycelial.haddock

haddock-html:
    /home/nicoluarte/Documents/repos/phd_DCCS/coursework/ABM/mushroomBrain/dist-newstyle/build/x86_64-linux/ghc-9.6.7/mycelial-0.1.0.0/doc/html/mycelial
