name:                 mushroomBrain
version:              0.1.0.0
visibility:           public
id:                   mushroomBrain-0.1.0.0-inplace
key:                  mushroomBrain-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            2025 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/mushroomBrain#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/mushroomBrain#readme>

abi:                  inplace
exposed:              True
exposed-modules:
    MycelialPhysics MycelialSimulation MycelialState MycelialStrategy

hidden-modules:       Lib Paths_mushroomBrain
import-dirs:
    C:\Users\DCCS5\Documents\GitHub\phd_DCCS_linux\coursework\ABM\mushroomBrain\dist-newstyle\build\x86_64-windows\ghc-9.12.2\mushroomBrain-0.1.0.0\build

library-dirs:
    C:\Users\DCCS5\Documents\GitHub\phd_DCCS_linux\coursework\ABM\mushroomBrain\dist-newstyle\build\x86_64-windows\ghc-9.12.2\mushroomBrain-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

library-dirs-static:
    C:\Users\DCCS5\Documents\GitHub\phd_DCCS_linux\coursework\ABM\mushroomBrain\dist-newstyle\build\x86_64-windows\ghc-9.12.2\mushroomBrain-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

dynamic-library-dirs:
    C:\Users\DCCS5\Documents\GitHub\phd_DCCS_linux\coursework\ABM\mushroomBrain\dist-newstyle\build\x86_64-windows\ghc-9.12.2\mushroomBrain-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

data-dir:
    C:\Users\DCCS5\Documents\GitHub\phd_DCCS_linux\coursework\ABM\mushroomBrain\.

hs-libraries:         HSmushroomBrain-0.1.0.0-inplace
include-dirs:         C:\ghcup\msys64\mingw64\include
depends:
    base-4.21.0.0-55e3 mtl-2.3.1-46e9
    random-1.3.1-ab7cd9c1eab0f8fe5e9f7faf4434615f34c085c4

haddock-interfaces:
    C:\Users\DCCS5\Documents\GitHub\phd_DCCS_linux\coursework\ABM\mushroomBrain\dist-newstyle\build\x86_64-windows\ghc-9.12.2\mushroomBrain-0.1.0.0\doc\html\mushroomBrain\mushroomBrain.haddock

haddock-html:
    C:\Users\DCCS5\Documents\GitHub\phd_DCCS_linux\coursework\ABM\mushroomBrain\dist-newstyle\build\x86_64-windows\ghc-9.12.2\mushroomBrain-0.1.0.0\doc\html\mushroomBrain
